feat(pulsar): support pulsar and pulsar-tuya data source (#3378)
* feat(pulsar): support pulsar and pulsar-tuya data source

Closes [TS-7448](https://jira.taosdata.com:18080/browse/TS-7448)

* chore: and and depends on install-protoc for taosx/agent

* chore: fix clippy error

* chore: install protoc in docker dev image [ci skip]

* fix(legacy): fix 0x2602 invalid column name vgroup_id when use stables in cloud

```bash
taosx run\
  -f "taos+https://gw.us-central-1.gcp.cloud.tdengine.com/prod?token=xxx&schema=only&stables=windspeeds,trackers,snowdepths" \
  -t taos:///prod
```

Error: [0x2602] Internal error: `Invalid column name: vgroup_id`

Caused by:
    Internal error: `Invalid column name: vgroup_id`

---------

Co-authored-by: Linhe Huo <linhehuo@gmail.com>