fix(pi): fix panic error
05/24 16:00:40.220579 ERROR [taosx:578] DTID:3c2a [put_stream{task.id=612 remote="192.168.32.28:57666"}->consume_lush_record_with_transform{trace.id=0x3c2a00000003}] panic occurred. panicked at /home/huolinhe/Projects/taosdata/taosx/taosx-core/src/plugins/sink/mod.rs:965:33:
Cannot block the current thread from within a runtime. This happens because a function attempted to block the current thread while the thread is being used to drive asynchronous tasks. disabled backtrace